name: Continuous Deployment
on:
  workflow_dispatch:
  push:
    branches:
      - production
    paths-ignore:
      - .gitignore
      - README.md
      - start-database.sh

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: executing deploy via ssh
        uses: appleboy/ssh-action@v1.0.3
        # env:
        #   PATH: ${{secrets.PATH}}
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASS}}
          script: |
            cd docker_compose_struct/site-struct-2024/
            git pull
            docker compose up -d
