name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - teste-gh-actions
    paths-ignore:
      - .gitignore
      - README.md
      - start-database.sh

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: executing deploy via ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASS}}
          shell: bash
          run: |
            cd docker_compose_struct/
            git pull
            cd site-struct-2024-teste/

            execute_with_retry() {
              local retries=$1
              local timeout=$2
              local command=$3
              local success=false
              while [ $retries -gt 0 ]; do
                if timeout $timeout $command; then
                  echo "$command successful!"
                  success=true
                  break
                else
                  echo "$command failed, retrying..."
                  ((retries--))
                fi
              done
              if [ "$success" = false ]; then
                echo "$command failed after all retries"
                return 1
              fi
            }

            execute_with_retry 1 5m "docker compose build web"

            execute_with_retry 1 5m "docker compose up -d"
